parameters:
  - name: serviceConnection
    type: string
  - name: backendResourceGroup
    type: string
  - name: backendStorageAccount
    type: string
  - name: organizationCode
    type: string
  - name: environmentGroup
    type: string
  - name: environment
    type: string
  - name: appName
    type: string
  - name: imageTag
    type: string
    default: ""
  - name: withHosting
    type: boolean
    default: true
  - name: apiServiceNames
    type: string
    default: '[]'
  - name: ingressPort
    type: number
    default: 80

steps:
  - checkout: infraGlobal
    displayName: Checkout Terraform Scripts
    path: infrastructure-global

  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: "1.14.8"

  - task: TerraformTaskV4@4
    displayName: Terraform Init
    inputs:
      provider: azurerm
      command: init
      workingDirectory: $(Pipeline.Workspace)/infrastructure-global/terraform/apps-web
      backendServiceArm: ${{ parameters.serviceConnection }}
      backendAzureRmResourceGroupName: ${{ parameters.backendResourceGroup }}
      backendAzureRmStorageAccountName: ${{ parameters.backendStorageAccount }}
      backendAzureRmContainerName: terraform-states-${{ parameters.environmentGroup }}
      backendAzureRmKey: apps-web-${{ parameters.appName }}-${{ parameters.environment }}.tfstate
      backendAzureRmUseAzureAdForAuthentication: true
      commandOptions: -backend-config=use_azuread_auth=true

  - task: TerraformTaskV4@4
    displayName: Terraform Plan
    inputs:
      provider: azurerm
      command: plan
      workingDirectory: $(Pipeline.Workspace)/infrastructure-global/terraform/apps-web
      environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}
      commandOptions: >-
        -var="organization_code=${{ parameters.organizationCode }}"
        -var="environment_group=${{ parameters.environmentGroup }}"
        -var="environment=${{ parameters.environment }}"
        -var="app_name=${{ parameters.appName }}"
        -var="image_tag=${{ parameters.imageTag }}"
        -var="with_hosting=${{ lower(format('{0}', parameters.withHosting)) }}"
        -var="ingress_port=${{ parameters.ingressPort }}"
        -out=$(Pipeline.Workspace)/tfplan
    env:
      TF_VAR_api_service_names: ${{ parameters.apiServiceNames }}

  - task: TerraformTaskV4@4
    displayName: Terraform Apply
    inputs:
      provider: azurerm
      command: apply
      workingDirectory: $(Pipeline.Workspace)/infrastructure-global/terraform/apps-web
      environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}
      commandOptions: $(Pipeline.Workspace)/tfplan
